version: '3.8'
name: jaeger-otel-clickhouse-backend
services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.4
    user: '101:101'
    container_name: clickhouse
    hostname: clickhouse
    volumes:
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./clickhouse/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - '127.0.0.1:8123:8123'
      - '127.0.0.1:9000:9000'
    depends_on:
      - clickhouse-keeper
  clickhouse-keeper:
    image: clickhouse/clickhouse-keeper:23.4
    user: '101:101'
    container_name: clickhouse-keeper
    hostname: clickhouse-keeper
    volumes:
      - ./clickhouse/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
    ports:
      - '127.0.0.1:9181:9181'
  otelcol:
    image: otel/opentelemetry-collector-contrib:0.97.0
    ports:
      - '127.0.0.1:4317:4317'
    volumes:
      - type: bind
        source: ./otelcol
        target: /config
    command:
      - --config
      - /config/config.yml
    depends_on:
      - clickhouse
  jaeger-query:
    image: jaegertracing/jaeger-query:1.56.0
    environment:
      SPAN_STORAGE_TYPE: grpc-plugin
    command:
      - --grpc-storage.server
      - jaeger-otel-clickhouse-backend:14482
    ports:
      - '127.0.0.1:16686:16686'
    depends_on:
      - jaeger-otel-clickhouse-backend
  jaeger-otel-clickhouse-backend:
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      JOCB_DB_HOST: clickhouse
      JOCB_DB_PORT: '9000'
      JOCB_DB_USER: default
      JOCB_ENABLE_TRACING: 'true'
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otelcol:4317
    ports:
      - '127.0.0.1:14482:14482'
    depends_on:
      - clickhouse
      - otelcol
