version: '3.8'
name: jaeger-otel-clickhouse-backend-dev
services:
  clickhouse:
    extends:
      file: docker-compose.yml
      service: clickhouse
    ports:
      - '127.0.0.1:8123:8123'
      - '127.0.0.1:9000:9000'
  otelcol:
    extends:
      file: docker-compose.yml
      service: otelcol
  jaeger-query:
    extends:
      file: docker-compose.yml
      service: jaeger-query
    command:
      - --grpc-storage.server
      - jaeger-otel-clickhouse-backend:14482
    depends_on:
      - jaeger-otel-clickhouse-backend
  jaeger-otel-clickhouse-backend:
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      JOCB_DB_HOST: clickhouse
      JOCB_DB_PORT: '9000'
      JOCB_DB_USER: default
      JOCB_ENABLE_TRACING: 'true'
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otelcol:4317
    ports:
      - '127.0.0.1:14482:14482'
    depends_on:
      clickhouse:
        condition: service_healthy
      otelcol:
        condition: service_started