apiVersion: v1
kind: Service
metadata:
  name: {{ include "jaeger-otel-clickhouse-backend.fullname" . }}
  labels:
    {{- include "jaeger-otel-clickhouse-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: 16686
      targetPort: http-ui
      protocol: TCP
      name: http-ui
  selector:
    {{- include "jaeger-otel-clickhouse-backend.selectorLabels" . | nindent 4 }}
