name: test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.22.0'

      - name: Test
        run: go test -v ./...
